// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrd4_YV2Q_uGf45P408bt5vM-9nATf9c',
    appId: '1:1093055286277:web:de71d5cdd0881b80ebe06c',
    messagingSenderId: '1093055286277',
    projectId: 'olx-flutter123',
    authDomain: 'olx-flutter123.firebaseapp.com',
    storageBucket: 'olx-flutter123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbzEYoaAjJFuG8KAMyAb5xODg3BrljHAw',
    appId: '1:1093055286277:android:be343b032aee713eebe06c',
    messagingSenderId: '1093055286277',
    projectId: 'olx-flutter123',
    storageBucket: 'olx-flutter123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKFsmYGlbmAAZW7U3wSDITfK3SOdYWfQ',
    appId: '1:1093055286277:ios:ca55ae18f1310ca7ebe06c',
    messagingSenderId: '1093055286277',
    projectId: 'olx-flutter123',
    storageBucket: 'olx-flutter123.appspot.com',
    iosClientId: '1093055286277-osm0rifusa8a4nnjabur8tql04k59vo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.julia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcKFsmYGlbmAAZW7U3wSDITfK3SOdYWfQ',
    appId: '1:1093055286277:ios:ca55ae18f1310ca7ebe06c',
    messagingSenderId: '1093055286277',
    projectId: 'olx-flutter123',
    storageBucket: 'olx-flutter123.appspot.com',
    iosClientId: '1093055286277-osm0rifusa8a4nnjabur8tql04k59vo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.julia',
  );
}
